### PR TITLE
Fixing broken image link

### PR DESCRIPTION
**Pull request by armandomistral**
fixes the broken path to the process overview image

### CODE REVIEW

**Review by armandomistral — COMMENTED** [review]
go

**Comment by jpangelle** [comment]
@armandomistral It does not look like there is a file with that name in the `images` directory: https://github.com/centrifuge/documentation/tree/develop/src/images

**Comment by jpangelle** [comment]
> @armandomistral It does not look like there is a file with that name in the `images` directory: https://github.com/centrifuge/documentation/tree/develop/src/images

ah nvm, I see now

**Comment by jpangelle** [comment]
I instead renamed the file to not use a space.

**Review by jpangelle — APPROVED** [review]
👍

**Pull request merged**
